version: '3.7'

services:
  main_cluster:
    image: cassandra:latest
    container_name: cassandra-cluster
    environment:
      - CASSANDRA_CLUSTER_NAME=ync-cluster
      - CASSANDRA_DC=spade
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    ports:
      - "9042:9042"
    networks:
      - ync

  initializer:
    image: ync-database:latest
    container_name: database-init
    environment:
      - CLUSTER_NAME=cassandra-cluster
    depends_on:
      - main_cluster
    networks:
      - ync

networks:
  ync:
    driver: bridge
