apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent:
    image:
      name: traefik
      tag: 2.9.10

    additionalArguments:
      # Enable Kubernetes CRD support for IngressRoute
      - "--providers.kubernetescrd=true"

    ingressRoute:
      - kind: IngressRoute
        name: redirect-root
        namespace: kube-system
        spec:
          entryPoints:
            - web
          routes:
            - match: PathPrefix(`/`)
              kind: Rule
              services:
                - name: cert-delivery
                  port: 30000

      - kind: IngressRoute
        name: redirect-api
        namespace: kube-system
        spec:
          entryPoints:
            - web
          routes:
            - match: PathPrefix(`/shop-api`)
              kind: Rule
              services:
                - name: shop-api
                  port: 31001

      - kind: IngressRoute
        name: redirect-root
        namespace: kube-system
        spec:
          entryPoints:
            - web
          routes:
            - match: PathPrefix(`/shop`)
              kind: Rule
              services:
                - name: shop-app
                  port: 30001