apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  namespace: ync
  labels:
    app: shop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: ync-shop-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: API_CONTACT_POINTS
          value: "82.67.90.121"
        - name: API_PORT
          value: "31001"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-app
  namespace: ync
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  clusterIP: 10.43.6.2
  selector:
    app: shop-app