apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
  labels:
    app: shop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
    spec:
      containers:
      - name: shop-api
        image: ync-shop-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: CASSANDRA_CONTACT_POINTS
          value: "10.43.6.0"
        - name: PORT
          value: "3001"
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: SHOP_API_COOKIE_SECRET
          # value: "some-string-will-do-the-trick"
        - name: PAYPAL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: SHOP_API_PAYPAL_CLIENT_ID
        # value: "?sandbox credentials"
        - name: PAYPAL_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: SHOP_API_PAYPAL_CLIENT_SECRET
          # value: "?sandbox credentials"
        - name: ZOHO_MAIL
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: SHOP_API_ZOHO_MAIL
          # value: "yng.corporation@gmail.com"
        - name: ZOHO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: SHOP_API_ZOHO_PASSWORD
          # value: "?*"

---
apiVersion: v1
kind: Service
metadata:
  name: shop-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  clusterIP: 10.43.6.1
  selector:
    app: shop-api