apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-delivery
  labels:
    app: cert-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-delivery
  template:
    metadata:
      labels:
        app: cert-delivery
    spec:
      containers:
      - name: cert-delivery
        image: ync-cert-delivery:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cert-delivery
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  clusterIP: 10.43.6.1
  selector:
    app: cert-delivery