apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/cassandra
    type: DirectoryOrCreate