apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  labels:
    app: cassandras
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pv-claim
  labels:
    app: cassandra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  labels:
    app: cassandra
data:
  cassandra.yaml: |
    #   See https://cassandra.apache.org/doc/latest/configuration/ for
    #   full explanations of configuration directives
    authenticator: PasswordAuthenticator

  keyspace.sh: |
    #!/bin/bash

    for cql-script in `ls /etc/init.d/cql/*/*.cql`; do
        cqlsh -u admin -p admin -f ${cql-script}
    done