apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  labels:
    app: shop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: ync-shop-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: API_CONTACT_POINT
          value: "10.43.6.1"
        - name: API_PORT
          value: "15779"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 15778
  clusterIP: 10.43.6.2
  selector:
    app: shop-app