apiVersion: apps/v1
kind: Pod
metadata:
    name: cassandra-cluster
    labels:
        app: cassandra-cluster
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cassandra
    template:
        metadata:
            labels:
                app: cassandra
        spec:
            volumes:
                - name: cassandra-cql
                  configMap:
                    name: cassandra-cql
            containers:
                name: cassandra
                image: cassandra:latest
                ports:
                    - containerPort: 9042
                volumeMounts:
                        name: cassandra-cql
                        mountPath: "/scripts"
                        readOnly: true
                        readinessProbe:
                            exec:
                                command:
                                    - /bin/bash
                                    - -c
                                    - cqlsh -e "DESC KEYSPACES"
                            initialDelaySeconds: 60
                            timeoutSeconds: 5
                            periodSeconds: 10
                            failureThreshold: 6
                        lifecycle:
                            postStart:
                                exec:
                                    command: ["/bin/bash", "-c", "while ! cqlsh -f '/scripts/store.cql'; do sleep 5; done"]
