apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    run: cassandra
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ync-database
spec:
  selector:
    matchLabels:
      run: ync-database
  replicas: 2
  template:
    metadata:
      labels:
        run: ync-database
    spec:
      containers:
      - name: ync-database
        image: nginx
        ports:
        - containerPort: 80

