apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
    namespace: ync-app
spec:
  clusterIP: None
  selector:
    app: cassandra
  ports:
  - port: 9042
    targetPort: cql
