apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ync-node-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: CASSANDRA_CONTACT_POINTS
          value: 10.100.6.7
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: node
#   labels:
#     app: node
# spec:
#   type: NodePort
#   ports:
#     - port: 3000
#       targetPort: 3000
#   selector:
#     name: node