apiVersion: batch/v1
kind: Job
metadata:
  name: ync-init-keyspace
spec:
  template:
    spec:
      containers:
      - name: ync-init-keyspace
        image: ync-job:latest
        imagePullPolicy: Never
        args: ["keyspace", "all"]
        env:
        - name: CASSANDRA_CONTACT_POINTS
          value: "10.43.6.0"
      restartPolicy: Never
  backoffLimit: 4